name: Build
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build cargo package and deb file
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build -o amd64-bin
      - run: nix build .#deb -o amd64-deb
      # - run: nix build --system aarch64-linux -o arm-bin
      # - run: nix build .#deb --system aarch64-linux -o arm-deb

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            amd64-bin/bin/h8r
            amd64-deb/h8r.deb
