name: Build
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build cargo package and deb file
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-24.04
            output-suffix: amd64
          - arch: aarch64
            runner: ubuntu-24.04-arm
            output-suffix: arm64
    runs-on: ${{ matrix.runner }}
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build binary
        run: nix build -o ${{ matrix.output-suffix }}
      - name: Build deb package
        run: nix build .#deb -o ${{ matrix.output-suffix }}-deb

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.arch }}
          path: |
            ${{ matrix.output-suffix }}-bin/bin/h8r
            ${{ matrix.output-suffix }}-deb/h8r.deb
