name: Build
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build cargo package and deb file
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build
      - uses: actions/upload-artifact@v4
        with:
          name: cargo-build
          path: result/bin/h8r

      - run: nix build .#deb -o deb
      - uses: actions/upload-artifact@v4
        with:
          name: debian
          path: deb/h8r.deb
